version: '3.7'

services:
  serverless-babel-starter:
    build: .
    ports:
      - '4000:4000'
    environment:
      - AWS_ACCESS_KEY_ID=YOUR_AWS_ACCESS_KEY
      - AWS_SECRET_ACCESS_KEY=YOUR_AWS_SECRET_KEY
      - AWS_DEFAULT_REGION=eu-west-1
    container_name: serverless-babel-starter
    volumes:
      - ./src/:/usr/src/app/src
    command: yarn serve:watch
